language: node_js
node_js:
  - "12"

branchs:
  only:
    - master

cache:
  directories:
    - node_modules

services:
  - docker

install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t dockerofliuyi/my-web:latest .
  - docker push dockerofliuyi/my-web:latest