name: my-web
on: 
  push:
    branchs:
      - master

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: install
      run: npm install
  
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
    - name: build
      run: |
        npm run build
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker build -t dockerofliuyi/my-web:latest .
        docker push dockerofliuyi/my-web:latest