name: my-web
on:
  push:
    branchs:
      - master  # 只在master上push触发部署
    paths-ignore:  # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest  # 使用ubuntu系统镜像运行自动化脚本
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        # path: ~/.npm
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install
      if: steps.cache-npm.outputs.cache-hit != 'true'
      run: npm install

    - name: Build
      run: |
        npm run build
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker build -t dockerofliuyi/my-web:latest .
        docker push dockerofliuyi/my-web:latest

    - name: Deploy
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd docker-compose
          docker-compose pull info
          docker-compose stop info
          docker-compose rm -f info
          docker-compose up -d info
          docker image prune -a -f
