name: my-web
on: 
  push:
    branchs:
      - master

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3

    - name: Install
      run: npm install

    - name: Build
      run: |
        npm run build
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker build -t dockerofliuyi/my-web:latest .
        docker push dockerofliuyi/my-web:latest

    - name: Deploy
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /www/server/docker-compose
          docker-compose pull info
          docker-compose stop info
          docker-compose rm info
          docker-compose up -d info
